apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.17.1
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        replicaCount: 1
        podDnsConfig:
          nameservers:
            - 9.9.9.9
            - 1.1.1.1
        extraArgs:
          - --enable-certificate-owner-ref
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=9.9.9.9:53,1.1.1.1:53
      version: v3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
