apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/oliverziegert/keptn-playground.git'
    path: prometheus
    targetRevision: main
  destination:
    server: 'keptn-system'
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true