apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 67.10.0
    helm:
      releaseName: prometheus
      values: >-
        kubeControllerManager:
          service:
            port: 10257
            targetPort: 10257
          serviceMonitor:
            https: true
            insecureSkipVerify: true
          service:
            port: 2381
            targetPort: 2381
        alertmanager:
          enabled: true
        prometheus:
          prometheusSpec:
            enableAdminAPI: true
        grafana:
          adminPassword: admin
          enabled: true
          additionalDataSources:
            - orgId: 1
              uid: jaeger
              name: Jaeger
              type: jaeger
              typeName: Jaeger
              typeLogoUrl: public/app/plugins/datasource/jaeger/img/jaeger_logo.svg
              access: proxy
              url: http://jaeger-query.keptn-system.svc.cluster.local:16686
              user: ''
              database: ''
              basicAuth: false
              isDefault: false
              jsonData:
                spanBar: 
                  type: None
              readOnly: false
        defaultRules:
          create: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
