apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/oliverziegert/keptn-playground.git'
    path: keptn/config
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keptn-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true