apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn-keptn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keptn
    repoURL: 'https://charts.lifecycle.keptn.sh'
    targetRevision: 0.3.0
    helm:
      releaseName: keptn
      values: >-
        certManager:
          enabled: false
        lifecycleOperator:
          enabled: true
        metricsOperator:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keptn-system
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true
