apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    targetRevision: 0.83.0
    helm:
      releaseName: opentelemetry-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opentelemetry-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
