apiVersion: options.keptn.sh/v1alpha1
kind: KeptnConfig
metadata:
  name: keptnconfig-sample
spec:
  OTelCollectorUrl: 'opentelemetry-collector-collector:4317'
  keptnAppCreationRequestTimeoutSeconds: 30