apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  config: |
    receivers:
      # Make sure to add the otlp receiver.
      # This will open up the receiver on port 4317
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 5s
              static_configs:
                - targets: ['keptn-lifecycle-operator-metrics-service:2222']
    processors:
    extensions:
      health_check: {}
    exporters:
      otlp:
        endpoint: "jaeger-collector:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
      logging:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]

        metrics:
          receivers: [otlp,prometheus]
          processors: []
          exporters: [prometheus, logging]